== JAX-RS Server

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-server</artifactId>
<version>{revnumber}</version>
----

This artifact makes available two *JAX-RS* server _features_ to implement JAX-RS server resources <<Authentication>> and <<Authorization>> using platform foundation APIs, such as link:holon-core.html#Realm[Realm].

[[Authentication]]
=== Authentication

The link:{apidir}/com/holonplatform/jaxrs/server/auth/AuthenticationFeature.html[AuthenticationFeature^] can be registered in a JAX-RS server configuration context to enable authentication support using the core link:{coreapidir}/com/holonplatform/auth/annotations/Authenticate.html[Authenticate^] annotation.

When this feature is enabled, the standard JAX-RS `SecurityContext` of every request will be replaced with an link:{coreapidir}/com/holonplatform/auth/AuthContext.html[AuthContext^] compatible implementation, which will be used to perform authentication when required.

NOTE: See link:holon-core.html#Auth[Authentication and authorization] documentation for information about the platform authentication and authorization architecture, API and components.

The JAX-RS resource classes and/or methods annotated with `@Authenticate` will be protected from unauthorized
access, performing client authentication using the `AuthContext` security context setted up by this feature as described above.

When authentication informations provided by a client for an `@Authenticate` annotated resource are missing or invalid, a `401 - Unauthorized` status response is returned, including a `WWW_AUTHENTICATE` header for each allowed authentication scheme, if any.

==== `Realm` configuration

The feature relies on a `Realm` to perform authentication operations, which must be available either:

* From a suitable JAX-RS `ContextResolver` which returns the `Realm` instance
* Or as a platform standard holon-core.html#Context[Context] resource with default `Realm` context key (i.e. `com.holonplatform.auth.Realm`)

==== Authentication schemes

Allowed authentication *schemes* can be specified using the `schemes()` attribute of the `@Authenticate` annotation attribute. If any scheme is specified for a resource, a scheme-matching link:{coreapidir}/com/holonplatform/auth/AuthenticationToken.AuthenticationTokenResolver.html[AuthenticationTokenResolver^] must be registered in `Realm` to perform authentication with given scheme.

[[Authorization]]
=== Authorization

TODO
