== JAX-RS Server

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-server</artifactId>
<version>{revnumber}</version>
----

This artifact deals with JAX-RS server resources <<Authentication>> and <<Authorization>>, using platform foundation APIs, such as link:holon-core.html#Realm[Realm].

[[Authentication]]
=== Authentication

The link:{apidir}/com/holonplatform/jaxrs/server/auth/AuthenticationFeature.html[AuthenticationFeature^] can be used in a JAX-RS server to enable authentication support using the core link:{coreapidir}/com/holonplatform/auth/annotations/Authenticate.html[Authenticate^] annotation.

The feature is automatically registered for *Jersey* and *Resteasy* server runtimes using Java Service extensions and auto-discoverable. To explicitly disable the feature, the `holon.jaxrs.server.disable-authentication` property name can be used, registering it as a the server configuration property name (with an arbitraty not null value).

When this feature is enabled, the standard JAX-RS `SecurityContext` of every request will be replaced with an link:{coreapidir}/com/holonplatform/auth/AuthContext.html[AuthContext^] compatible implementation, which will be used to perform authentication when required.

NOTE: See link:holon-core.html#Auth[Authentication and authorization] documentation for information about the platform authentication and authorization architecture, API and components.

The JAX-RS resource classes and/or methods annotated with `@Authenticate` will be protected from unauthorized
access, performing client authentication using the `AuthContext` security context setted up by this feature as described above.

When authentication informations provided by a client for an `@Authenticate` annotated resource are missing or invalid, a `401 - Unauthorized` status response is returned, including a `WWW_AUTHENTICATE` header for each allowed authentication scheme, if any.

==== `Realm` configuration

The feature relies on a `Realm` to perform authentication operations, which must be available either:

* From a suitable JAX-RS `ContextResolver` which returns the `Realm` instance
* Or as a platform standard link:holon-core.html#Context[Context] resource with default `Realm` context key (i.e. `com.holonplatform.auth.Realm`)

==== Authentication schemes

Allowed authentication *schemes* can be specified using the `schemes()` attribute of the `@Authenticate` annotation attribute. If any scheme is specified for a resource, a scheme-matching link:{coreapidir}/com/holonplatform/auth/AuthenticationToken.AuthenticationTokenResolver.html[AuthenticationTokenResolver^] must be registered in `Realm` to perform authentication with given scheme.

See link:holon-core.html#MessageAuthenticator[MessageAuthenticator] for information about _message authenticators_ and builtin authenticators for HTTP schemes like `Basic` and `Bearer`.

==== Example

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleAuth.java[tag=auth,indent=0]
----
<1> JAX-RS endpoint resource protected using `@Authenticate` and `Basic` HTTP authentication scheme
<2> JAX-RS endpoint resource with only one protected method
<3> This method is not protected
<4> Only this method of the resource is protected using `@Authenticate` and `Basic` HTTP authentication scheme
<5> `AccountProvider` to provide available `Account` s to the Realm 
<6> Build a `Realm` to be used for resource access authentication
<7> Add a _resolver_ for HTTP `Basic` scheme authentication messages
<8> Set the realm _authenticator_ using the previously defined `AccountProvider`
<9> Create a JAX-RS `ContextResolver` to provide the `Realm` instance to use
<10> Register the Realm `ContextResolver` in JAX-RS application (for example, using a Jersey `ResourceConfig`)

[[Authorization]]
=== Authorization

When a `SecurityContext` is setted up, for example using the <<Authentication>> feature, it can used to check if an account is authenticated and perform role-based access control.

For example, to use stardard `javax.annotation.security` annotations on resource classes for role-based access control, you can:

* In *Jersey*, register the standard `RolesAllowedDynamicFeature` in server resources configuration.
* In *Resteasy*, activate the role-based security access control setting a servlet the context parameter `resteasy.role.based.security` to `true`.


