[[JaxrsSpringBoot]]
== Spring Boot integration

The JAX-RS module *Spring Boot* integration provides auto-configuration facilities to:

* Auto-configure a <<JaxrsRestClient>>.
* Auto-configure the <<Authentication>> feature when a `Realm` type bean is detected.
* Simplify the <<Jersey>> auto-configuration.
* Enable the <<Resteasy>> auto-configuration.

Futhermore, a set of <<JaxrsStarters>> are available to provide a quick JAX-RS server and/or client application setup using the Maven dependency system.

[[Client]]
=== JAX-RS Client

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-spring-boot-client</artifactId>
<version>{revnumber}</version>
----

This artifact provides a Spring Boot auto-configuration class to automatically register a link:{apidir}/com/holonplatform/jaxrs/spring/boot/JaxrsClientBuilder.html[JaxrsClientBuilder^] bean, which can be used to obtain a configured `javax.ws.rs.client.Client` instance.

Besides the `JaxrsClientBuilder` bean type, a `RestClient` factory is automatically registered, allowing to simply obtain a `RestClient` API instance through the `RestClient.create()` static method, using the `javax.ws.rs.client.Client` instance provided by the `JaxrsClientBuilder` API.

TIP: See <<JaxrsRestClient>> for more information about the JAX-RS `RestClient` API.

To customize the JAX-RS `ClientBuilder` used to obtain the concrete `javax.ws.rs.client.Client` instances, the link:{apidir}/com/holonplatform/jaxrs/spring/boot/JaxrsClientCustomizer.html[JaxrsClientCustomizer^] interface can be used. 

Any Spring context bean which implement the `JaxrsClientCustomizer` interface will be auto-detected and the `customize(ClientBuilder clientBuilder)` method will be invoked when a `ClientBuilder` is created.

To replace the default `ClientBuilder` instance lookup/creation strategy, a link:{apidir}/com/holonplatform/jaxrs/spring/boot/JaxrsClientBuilderFactory.html[JaxrsClientBuilderFactory^] bean type can be declared in Spring context, which will be used by the `JaxrsClientBuilder` to create a new JAX-RS `ClientBuilder` instance.

For example, given a Spring Boot application with the following configuration:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleClientBuilder.java[tag=clientbuilder1,indent=0]
----
<1> Add a `JaxrsClientCustomizer` which registers a property in JAX-RS `ClientBuilder`
<2> Add a `JaxrsClientCustomizer` which setup the `ClientBuilder` to use a *SSLContext* with a _trust all_ manager and dummy host name verifier

A JAX-RS `Client` (and a `RestClient` API backed by the Client), configured according to the declared customizers, can be obtained as follows:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleClientBuilder.java[tag=clientbuilder2,indent=0]
----
<1> Use the `JaxrsClientBuilder` to obtain a new JAX-RS `Client` instance
<2> Use the `RestClient.create()` static method to obtain a `RestClient` which uses a JAX-RS `Client` obtained from the `JaxrsClientBuilder`

[[Jersey]]
=== Jersey

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-spring-boot-jersey</artifactId>
<version>{revnumber}</version>
----

This artifact provides link:https://github.com/jersey[Jersey^] Spring Boot auto-configuration classes to simplify the Jersey JAX-RS runtime configuration, the JAX-RS server resources registration and the authentication and authorization features setup.

==== Automatic JAX-RS server resources registration

When the `holon-jaxrs-spring-boot-jersey` is available in classpath, any Spring context *bean* annotated with the `@Path` or `@Provider` JAX-RS annotations is automatically registered as a JAX-RS server resource, using the default `ResourceConfig` Jersey configuration bean.

IMPORTANT: For `@Provider` annotated bean classes auto-registration, only *singleton* scoped beans are allowed.

Furthermore, a default Jersey `ResourceConfig` type bean is created when no other `ResourceConfig` type bean is available in the Spring context.

To disable the automatic JAX-RS bean resources registration, the `holon.jersey.bean-scan` Spring boot application property can be used: when setted to `false`, this auto-configuration feature will be disabled.

==== Handling the `jersey.config.servlet.filter.forwardOn404` configuration property

When Jersey is registered as a Servlet _filter_, the Spring Boot application configuration property  `holon.jersey.forwardOn404` is available to set the (boolean) value of the standard `jersey.config.servlet.filter.forwardOn404` configuration property.

When setted to `true`, it configures the Jersey filter in order to forward the requests for URLs it doesn't know, instead of responding with a `404` error code.

This can be useful when the Jersey filter is mapped to the root context path but other servlets are mapped to a sub path.

==== Authentication and authorization

When a `Realm` type bean is detected in Spring context, the JAX-RS server is automatically configured to support *authentication*, registering the <<Authentication>> feature (and so enabling the `@Authenticate` annotation detection), and *authorization*, relying on standard `javax.annotation.security.*` annotations.

The auto-configuration class perfoms the following operations:

* Registers a `ContextResolver` providing the `Realm` bean instance.
* Registers the <<Authentication>> feature.
* Registers the default Jersey link:https://jersey.github.io/apidocs/2.25/jersey/org/glassfish/jersey/server/filter/RolesAllowedDynamicFeature.html[RolesAllowedDynamicFeature^] to support `javax.annotation.security.*` annotations based authorization.

To disable this auto-configuration feature the `JerseyServerAutoConfiguration` class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={JerseyAuthAutoConfiguration.class})
----

[[Resteasy]]
=== Resteasy

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-spring-boot-resteasy</artifactId>
<version>{revnumber}</version>
----

This artifact provides link:http://resteasy.jboss.org[Resteasy^] Spring Boot auto-configuration classes to *automatically setup a Resteasy JAX-RS server runtime* and configure it using Spring Boot application configuration properties.

Furthermore, it provide auto-configuration classes to simplify the JAX-RS server resources registration and the authentication and authorization features setup.

==== Configuration

The link:{apidir}/com/holonplatform/jaxrs/spring/boot/resteasy/ResteasyConfig.html[ResteasyConfig^] class, which extends default JAX-RS `Application` class, can be used to register the JAX-RS resources, similarly to the `ResourceConfig` Jersey configuration class.

The `ResteasyConfig` must be declared as a singleton Spring bean to be used by the Resteasy auto-configuration classes. If a `ResteasyConfig` type bean is not available, a *default one* will be automatically created.

The Resteasy JAX-RS application path can be defined either using the default JAX-RS `@ApplicationPath` annotation on the
`ResteasyConfig` bean class or through the `holon.resteasy.application-path` configuration property. See <<ConfigurationProperties>> for a list of available configuration properties.

==== Resteasy configuration customization

Any Spring bean which implements the link:{apidir}/com/holonplatform/jaxrs/spring/boot/resteasy/ResteasyConfigCustomizer.html[ResteasyConfigCustomizer^] interface, is automatically discovered and its `customize` method is called, allowing to customize the `ResteasyConfig` instance before it is used.

==== Automatic JAX-RS server resources registration

Just like the <<Jersey>> auto-configuration classes, this module automatically register any Spring context *bean* annotated with the `@Path` or `@Provider` JAX-RS annotations as a JAX-RS server resource.

IMPORTANT: For `@Provider` annotated bean classes, only *singleton* scoped beans are allowed.

[[ConfigurationProperties]]
==== Resteasy configuration properties

The link:{apidir}/com/holonplatform/jaxrs/spring/boot/resteasy/ResteasyConfigurationProperties.html[ResteasyConfigurationProperties^] lists the configuration properties (with the `holon.resteasy` prefix) which can be used to setup the Resteasy auto-configuration, using standard Spring Boot configuration property sources.

TIP: Just like any other Spring Boot configuration property, the `holon.resteasy.*` properties can be specified in your inside your `application.properties` / `application.yml` file or as command line switches.

|===
|Name |Default value |Meaning

|_holon.resteasy._ *application-path*
|_no default_
|Path that serves as the base URI for the application. Overrides the value of `@ApplicationPath` if specified

|_holon.resteasy._ *type*
|`servlet`
|Resteasy integration type: `servlet` or `filter`

|_holon.resteasy._ *filter.order*
|`0`
|Resteasy filter chain order when integration type is `filter`

|_holon.resteasy._ *servlet.load-on-startup*
|`-1`
|Load on startup priority of the Resteasy servlet when integration type is `servlet`

|_holon.resteasy._ *init.*
|_no default_
|Init parameters to pass to Resteasy via the servlet or filter
|===

==== Authentication and authorization

When a `Realm` type bean is detected in Spring context, the JAX-RS server is automtically configured to support *authentication*, registering the <<Authentication>> feature (and so enabling the `@Authenticate` annotation detection), and *authorization*, relying on standard `javax.annotation.security.*` annotations.

The auto-configuration class perfoms the following operations:

* Registers a `ContextResolver` providing the `Realm` bean instance.
* Registers the <<Authentication>> feature.
* Set the `resteasy.role.based.security` context init parameter to `true` to enable `javax.annotation.security.*` annotations based authorization.

To disable this auto-configuration features, the `ResteasyAuthAutoConfiguration` class can be excluded:

[source, java]
----
@EnableAutoConfiguration(exclude={ResteasyAuthAutoConfiguration.class})
----

[[JaxrsStarters]]
=== Spring Boot starters

The following _starter_ artifacts are available to provide a quick JAX-RS server and/or client application setup using the Maven dependency system.

All the available _starters_ include the default Holon _core_ Spring Boot starters (see the documentation for further information) and the base Spring Boot starter (`spring-boot-starter`).

The *Jersey* _starters_ include the default Spring Boot Jersey starter (`spring-boot-starter-jersey`).

The *Resteasy* _starters_ include the default Spring Boot Web starter (`spring-boot-starter-web`).

The Maven *group id* for all the JAX-RS _starters_ is `com.holon-platform.jaxrs`. So you can declare a _starter_ in you `pom` dependencies section like this:

[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-starter-xxx</artifactId>
<version>{revnumber}</version>
----

==== JAX-RS client

|===
|Artifact id |Description

|`holon-starter-jersey-client`
|JAX-RS _client_ starter using *Jersey* and *Jackson* as JSON provider
|`holon-starter-jersey-client-gson`
|JAX-RS _client_ starter using *Jersey* and *Gson* as JSON provider
|`holon-starter-resteasy-client`
|JAX-RS _client_ starter using *Resteasy* and *Jackson* as JSON provider
|`holon-starter-resteasy-client-gson`
|JAX-RS _client_ starter using *Resteasy* and *Gson* as JSON provider
|===

==== JAX-RS server

|===
|Artifact id |Description

|`holon-starter-jersey`
|JAX-RS _server_ starter using *Jersey*, *Tomcat* as embedded servlet container and *Jackson* as JSON provider
|`holon-starter-jersey-gson`
|JAX-RS _server_ starter using *Jersey*, *Tomcat* as embedded servlet container and *Gson* as JSON provider
|`holon-starter-jersey-undertow`
|JAX-RS _server_ starter using *Jersey*, *Undertow* as embedded servlet container and *Jackson* as JSON provider
|`holon-starter-jersey-undertow-gson`
|JAX-RS _server_ starter using *Jersey*, *Undertow* as embedded servlet container and *Gson* as JSON provider

|`holon-starter-resteasy`
|JAX-RS _server_ starter using *Resteasy*, *Tomcat* as embedded servlet container and *Jackson* as JSON provider
|`holon-starter-resteasy-gson`
|JAX-RS _server_ starter using *Resteasy*, *Tomcat* as embedded servlet container and *Gson* as JSON provider
|`holon-starter-resteasy-undertow`
|JAX-RS _server_ starter using *Resteasy*, *Undertow* as embedded servlet container and *Jackson* as JSON provider
|`holon-starter-resteasy-undertow-gson`
|JAX-RS _server_ starter using *Resteasy*, *Undertow* as embedded servlet container and *Gson* as JSON provider
|===
