[[Swagger]]
== Swagger / OpenAPI integration

_Swagger V2 Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-swagger-v2</artifactId>
<version>{revnumber}</version>
----

_Swagger/OpenAPI V3 Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-swagger-v3</artifactId>
<version>{revnumber}</version>
----

The `holon-jaxrs-swagger-v2` and `holon-jaxrs-swagger-v3` artifacts provide integration with the  link:http://swagger.io[Swagger^] _OpenAPI Specification_, for the *Swagger Version 2* and the *Swagger/OpenAPI Version 3* specifications respectively.

WARNING: The Holon Platform 5.1.x `holon-jaxrs-swagger` artifact is *deprecated* and should be replaced with the `holon-jaxrs-swagger-v2` artifact. The `holon-jaxrs-swagger` is still available in Holon Platform version 5.2.x, acting as an alias only for backward compatibility purposes.

The integration facilities concerns the following aspects:

* A complete integration with the Holon Platform *Property model* data types, specifically with the link:holon-core.html#PropertyBox[PropertyBox^] type, ensuring a consistent representation and serialization using the Swagger/OpenAPI definition models. See <<PropertyBoxModel>>.

* A convenient `ApiReader` API to obtain a Swagger/OpenAPI definition from a set of API resource classes.  See <<ApiReader>>.

* A complete and highly configurable *Spring Boot* integration, with auto-configuration facilities for both *Jersey* and *Resteasy* JAX-RS runtimes. See <<SwaggerSpringBoot>>.

TIP: The Swagger/OpenAPI integration architecture is designed to be highly consistent between the Swagger/OpenAPI versions 2 and 3, so in most cases it is enough to put the `holon-jaxrs-swagger-v2` or the `holon-jaxrs-swagger-v3` artifact in classpath to enable the integration features. Or even both: see <<V2andV3>>.

[[PropertyBoxModel]]
=== `PropertyBox` data type support

When the `holon-jaxrs-swagger-v2` or the `holon-jaxrs-swagger-v3` artifact is in classpath, the Swagger/OpenAPI reader engine is automatically configured to support the `PropertyBox` type as API operations parameter or return type.

IMPORTANT: If you programmatically use the Swagger/OpenAPI reader or context configuration classes to generate the API definition model, you have to include a proper `ReaderListener` class in the API resource classes to ensure a consistent `PropertyBox` type handling. This class is available from the `CONTEXT_READER_LISTENER` static attribute of the  
link:{apidir}/com/holonplatform/jaxrs/swagger/v2/SwaggerV2.html[SwaggerV2^] interface for the Swagger V2 integration and of the link:{apidir}/com/holonplatform/jaxrs/swagger/v3/SwaggerV3.html[SwaggerV3^] interface for the Swagger/OpenAPI V3 integration.

TIP: When the <<SwaggerSpringBoot,Spring Boot integration>> is enabled or an <<ApiReader,ApiReader>> is used, the Swagger/OpenAPI engine is automatically configured for a consistent `PropertyBox` type support.

[[PropertySetRef]]
==== `PropertyBox` property set declaration

A `PropertyBox` type API parameter or return type is translated in a regular Swagger/OpenAPI _object_ type Model/Schema definition, listing all the properties of the `PropertyBox` *property set* as object attributes.

NOTE: By default, only the `Path` type properties are included in the API definition _models_/_schemas_, using the `Path` *name* as model/schema attribute name and the property *type* as model/schema attribute type.

Since a `PropertyBox` type class does not provide a fixed link:holon-core.html#PropertySet[PropertySet] decalration, the link:{coreapidir}/com/holonplatform/core/property/PropertySetRef.html[PropertySetRef^] *annotation has to be used* to declare the `PropertySet` to use to translate the `PropertyBox` type into an API model/schema definition. The annotation has to be placed on the `PropertyBox` type method parameters and/or method return types.

The `PropertySetRef` annotation *value* can be either:
* A class which contains the `PropertySet` instance as a `public static` field.
* A `PropertySet` type class: in this case, a new instance of such class will be used.

When the first option is used and more than one `PropertySet` type static field is available in the provided class, the *field* annotation attribute can be used to specify the field name to use.

[[Subjects]]
For example, given the following `SubjectModel` interface, which contains a data model declaration for a simple subject entity:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=model,indent=0]
----
<1> `PropertySet` definition

The `SUBJECT` field can be used as `PropertyBox` property set definition in a JAX-RS API endpoint like this:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=propertyset,indent=0]
----
<1> Declare the `PropertySet` to use for the `getById` operation *return type*, using the `PropertySetRef` annotation
<2> Declare the `PropertySet` to use for the `create` operation *body parameter*, using the `PropertySetRef` annotation

Since the `SUBJECT` field is the unique `PropertySet` type static field of the `SubjectModel` interface, no additional *field* name specification is required in the `PropertySetRef` annotation.

In this example, the generated API definition will look like this (using the YAML format):

.Swagger 2 specification:
[source, yaml]
----
swagger: "2.0"
paths:
  /subjects/{id}:
    get:
      operationId: "getById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          headers: {}
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int32"
              name:
                type: "string"
            title: "PropertyBox"
  /subjects:
    put:
      operationId: "create"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "object"
          properties:
            id:
              type: "integer"
              format: "int32"
            name:
              type: "string"
          title: "PropertyBox"
      responses:
        default:
          description: "successful operation"
definitions: {}
----

.Swagger/OpenAPI 3 specification:
[source, yaml]
----
openapi: 3.0.1
paths:
  /subjects/{id}:
    get:
      operationId: getById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                title: PropertyBox
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
  /subjects:
    put:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              title: PropertyBox
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
      responses:
        default:
          description: default response
          content:
            '*/*': {}
components:
  schemas: {}
----

See the next section to learn how to include a `PropertyBox` type model/schema in the Swagger API definition `definitions` (for Swagger V2) or `components/schemas` (for Swagger V3).

[[PropertyBoxModelDefinition]]
==== Creating a Swagger Model/Schema definition for a `PropertyBox` type

When the `PropertySetRef` annotation is used, a generic Swagger _object_ type model/schema definition is generated for each API response or API operation parameter, using the property set definition to generate the schema properties.

To include a `PropertyBox` type as a _named_ model/schema in the Swagger API definition (i.e. to create a type declaration in the `definitions` section for Swagger V2 or in the `components/schemas` section for Swagger V3), the link:{apidir}/com/holonplatform/jaxrs/swagger/annotations/ApiPropertySetModel.html[ApiPropertySetModel^] annotation can be used.

The `ApiPropertySetModel` *value* attribute is used to specify the model/schema _name_. When a `PropertyBox` type model is declared this way, its name will be used as a _reference_ in the API operation components which use it.

The `ApiPropertySetModel` annotation should be always used in conjunction with the `PropertySetRef` annotation, which provides the property set declaration.

TIP: To make the API enpoints code more readable and to ensure a consistent property set and model name definition, the `PropertySetRef` and `ApiPropertySetModel` annotations can be used as meta-annotations to create specific annotations to be used in the API endpoints code. See below for an example.

Taking the <<Subjects,Subjects>> example endpoint declaration, we can create a `Subject` annotation to declare the `PropertySet` to use and a model/schema definition named `Subject` this way:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=apimodel1,indent=0]
----
<1> `PropertySet` reference declaration
<2> Model/Schema *name* definition

Next, the `Subject` annotation is used in the JAX-RS endpoint instead of the simple `PropertySetRef` annotation:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=apimodel2,indent=0]
----
<1> Declare the `Subject` model definition for the `getById` operation *return type*
<2> Declare the `Subject` model definition for the `create` operation *body parameter*

The generated API definition will include a `Subject` model/schema definition and will look like this:

.Swagger 2 specification:
[source, yaml]
----
swagger: "2.0"
paths:
  /subjects/{id}:
    get:
      operationId: "getById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          headers: {}
          schema:
            $ref: "#/definitions/Subject"
  /subjects:
    put:
      operationId: "create"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Subject"
      responses:
        default:
          description: "successful operation"
definitions:
  Subject:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
    title: "Subject"
----

.Swagger/OpenAPI 3 specification:
[source, yaml]
----
openapi: 3.0.1
paths:
  /subjects/{id}:
    get:
      operationId: getById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
  /subjects:
    put:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
      responses:
        default:
          description: default response
          content:
            '*/*': {}
components:
  schemas:
    Subject:
      title: Subject
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
----

In the API definition, the API operation return types or body parameters annotated with the `Subject` annotation declarations provide a *reference* to the `Subject` model/schema definition.

[[ApiReader]]
=== Using the `ApiReader` to generate the API definition model

The link:{apidir}/com/holonplatform/jaxrs/swagger/ApiReader.html[ApiReader^] service can be used to directly generate a Swagger API definition model from a set of JAX-RS API resource classes, ensuring a consistent Swagger engine configuration with the Holon Platform property model support.

The `read(Set<Class<?>> classes)` method reads and generates a Swagger API definition model which includes the given API resource classes operations.

==== Swagger version 2 `ApiReader`

The link:{apidir}/com/holonplatform/jaxrs/swagger/v2/SwaggerV2.html[SwaggerV2^] entrypoint interface can be used to obtain an `ApiReader`, using a `SwaggerConfig` type configuration definition and providing a `io.swagger.models.Swagger` type API definition model.

Furthermore, the `SwaggerV2` interface provides a set of convenience methods to serialize the Swagger model using *JSON* (through the `asJson(...)` methods) or *YAML* (through the `asYaml(...)` methods).

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=apireaderv2,indent=0]
----
<1> Obtain a `ApiReader` using the provided configuration
<2> Generate the Swagger API model from given API resource classes
<3> Serialize the API model using JSON
<4> Serialize the API model using YAML

==== Swagger/OpenAPI version 3 `ApiReader`

The link:{apidir}/com/holonplatform/jaxrs/swagger/v3/SwaggerV3.html[SwaggerV3^] entrypoint interface can be used to obtain an `ApiReader`, using a `OpenAPIConfiguration` type configuration definition and providing a `io.swagger.v3.oas.models.OpenAPI` type API definition model.

Furthermore, the `SwaggerV3` interface provides a set of convenience methods to serialize the Swagger/OpenAPI model using *JSON* (through the `asJson(...)` methods) or *YAML* (through the `asYaml(...)` methods).

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=apireaderv3,indent=0]
----
<1> Obtain a `ApiReader` using the provided configuration
<2> Generate the OpenAPI model from given API resource classes
<3> Serialize the API model using JSON
<4> Serialize the API model using YAML

[[SwaggerSpringBoot]]
=== Swagger Spring Boot integration and auto configuration

The `holon-jaxrs-swagger-v2` and `holon-jaxrs-swagger-v3` artifacts provide a set of *Spring Boot* auto-configuration classes to automatically configure *Swagger API definition JAX-RS endpoints* for Swagger/OpenAPI version 2 and version 3 respectively, using the Spring Boot application JAX-RS API endpoints classes as API definition sources.

Both *Jersey* and *Resteasy* JAX-RS runtimes are supported.

Obviously, all the standard *Swagger annotations* are supported for the API definition configuration. See link:https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X[Swagger specification version 2 annotations^] and link:https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations[Swagger/OpenAPI specification version 3 annotations^] for information about the available annotations.

==== Prerequisites

To enable the Swagger Spring Boot auto-configuration facilities, just include in classpath the `holon-jaxrs-swagger-v2` artifact for Swagger version 2 integration and `holon-jaxrs-swagger-v3` artifact for Swagger/OpenAPI version 3 integration.

NOTE: It is perfectly safe to include *both* `holon-jaxrs-swagger-v2` and `holon-jaxrs-swagger-v3` artifacts in order to enable the Swagger version 2 and version 3 integration simultaneously. See <<V2andV3>> for JAX-RS API definition endpoints _path_ naming considerations.

The Swagger API definition endpoints auto-configuration is triggered when the following conditions are satisfied:

* When the *Jersey* JAX-RS runtime is used, a `org.glassfish.jersey.server.ResourceConfig` type bean must be available in context.

* When the *Resteasy* JAX-RS runtime is used, a `com.holonplatform.jaxrs.spring.boot.resteasy.ResteasyConfig` type bean must be available in context.

TIP: When the Holon Platform JAX-RS Spring Boot integration is available, a `ResourceConfig` or `ResteasyConfig` type bean can be automatically configured, including the automatic registration of the `@Path` annotated JAX-RS endpoint classes declared as Spring beans. See the link:holon-jaxrs.html#JaxrsSpringBoot[JAX-RS Spring Boot integration documentation^] section.

==== Default API endpoints configuration strategy

By default, any `@Path` annotated JAX-RS endpoint class registered in the JAX-RS `javax.ws.rs.core.Application` is included in the Swagger API definition.

A JAX-RS *Swagger API definition* endpoint class in generated and registered in the current JAX-RS runtime to provide the Swagger API definition either in *JSON* or *YAML* format.

By default, the Swagger API definition endpoint will be available at the `/api-docs` path and a `type` named URL *query parameter* can be used to declare the API output format, which can be either `json` or `yaml`.

Depending on the `holon-jaxrs-swagger-v2` or `holon-jaxrs-swagger-v3` artifact presence in classpath, the Swagger API definition output will be provided either in version 2 or version 3 specification format.

For example, given a Maven project whith the following dependencies in the `pom.xml` file:

[source, xml, subs="attributes+"]
----
<dependencies>
  <!-- Optional Holon JAX-RS starter using Jersey -->
  <dependency>
    <groupId>com.holon-platform.jaxrs</groupId>
    <artifactId>holon-starter-jersey</artifactId>
    <version>{revnumber}</version>
  </dependency>
  <!-- Swagger V3 integration -->
  <dependency>
    <groupId>com.holon-platform.jaxrs</groupId>
    <artifactId>holon-jaxrs-swagger-v3</artifactId>
    <version>{revnumber}</version>
  </dependency>
</dependencies>
----

A Swagger API definition endpoint will be automatically configured and mapped to the `/api-docs` path. Supposing the application is available from `localhost`, the API definition can be obtained from the following URL:

.JSON format:
[source, text]
----
http://localhost/api-docs?type=json
----

.YAML format:
[source, text]
----
http://localhost/api-docs?type=yaml
----

The Swagger Spring Boot integration can be widely configured, either using explicit configuration beans or the `holon.swagger.*` configuration property set. See the next sections for the available configuration options.

[[ApiEndpointPath]]
==== API definition endpoint path

By default, the Swagger API definition endpoint is mapped to the `/api-docs` path.

See the <<BeanConfiguration>> section or the <<PropertiesConfiguration>> section to learn how to specify the Swagger API definition endpoint path, either using the `@ApiConfiguration` bean annotation or the `holon.swagger.path` application configuration property.

[[ApiEndpointType]]
==== API definition endpoint types

The following Swagger API definition JAX-RS endpoint types are available and listed in the link:{apidir}/com/holonplatform/jaxrs/swagger/ApiEndpointType.html[ApiEndpointType^] enumeration:

|===
|Type |Description |Parameters

|`QUERY_PARAMETER`
|Swagger API definition endpoint which uses a `type` named URL *query parameter* for the API output format declaration.
|The `type` query parameter valid values are `json` for JSON format and `yaml` for YAML format. If not specified, the JSON format is used by default.

|`PATH_PARAMETER`
|Swagger API definition endpoint which uses a *path parameter* for the API output format declaration. The path parameter value must be prefixed by a dot (`.`). For example: `http://localhost/api-docs.json` or `http://localhost/api-docs.yaml`.
|The path parameter valid values are `json` for JSON format and `yaml` for YAML format. If not specified, the JSON format is used by default.

|`ACCEPT_HEADER`
|Swagger API definition endpoint which uses the `Accept` *request header* value for the API output format declaration.
|The `Accept` request header valid values are `application/json` for JSON format and `application/yaml` for YAML format. If not specified, the JSON format is used by default.

|===

The `QUERY_PARAMETER` type is the *default* Swagger API definition endpoint type. See the <<BeanConfiguration>> section or the <<PropertiesConfiguration>> section to learn how to specify the Swagger API definition endpoint type, either using the `@ApiConfiguration` bean annotation or the `holon.swagger.type` application configuration property.

[[JaxrsScannerType]]
==== API resources scan strategy

The following strategies are available to detect the JAX-RS API resource classes to include in the Swagger API definition (listed in the link:{apidir}/com/holonplatform/jaxrs/swagger/JaxrsScannerType.html[JaxrsScannerType^] enumeration):

|===
|Type |Strategy 

|`APPLICATION`
|Only the `@Path` annotated resource classes registered in the JAX-RS `Application` will be included in the Swagger API definition.

|`ANNOTATION`
|All the `@Path` annotated resource classes available from the Spring application scan paths will be included in the Swagger API definition.

|`APPLICATION_AND_ANNOTATION`
|Both the `@Path` annotated resource classes registered in the JAX-RS `Application` and the `@Path` annotated resource classes available from the Spring application scan paths will be included in the Swagger API definition.

|===

By default, the `APPLICATION` type scan strategy is used. See the <<BeanConfiguration>> section or the <<PropertiesConfiguration>> section to learn how to specify the API definition resources scan strategy, either using the `@ApiConfiguration` bean annotation or the `holon.swagger.scanner-type` application configuration property.

[[PropertiesConfiguration]]
==== API and endpoints configuration using application properties

The `holon.swagger.*` configuration property set can be used to configure the Swagger API definition and the Swagger API endpoints.

The link:{apidir}/com/holonplatform/jaxrs/swagger/spring/SwaggerConfigurationProperties.html[SwaggerConfigurationProperties^] class represents the Spring Boot application properties which are available for configuration.

*1. Swagger auto-configuration enabling:*

|===
|Property name |Type |Meaning |Default

|holon.swagger.*enabled*
|Whether the Swagger API definition endpoints auto-configuration is enabled
|Boolean
|`true`

|===

*2. API endpoint configuration:*

|===
|Property name |Type |Meaning |Default

|holon.swagger.*path*
|The Swagger API definition endpoint JAX-RS path
|String
|`api-docs`

|holon.swagger.*type*
|The Swagger API definition endpoint type. Must be one of the link:{apidir}/com/holonplatform/jaxrs/swagger/ApiEndpointType.html[ApiEndpointType^] enumeration values. See <<ApiEndpointType>>.
|String
|`QUERY_PARAMETER`

|holon.swagger.*scanner-type*
|The Swagger API definition resource classes scan strategy. Must be one of the link:{apidir}/com/holonplatform/jaxrs/swagger/JaxrsScannerType.html[JaxrsScannerType^] enumeration values. See <<JaxrsScannerType>>.
|String
|`APPLICATION`

|holon.swagger.*context-id*
|The context id to which the generated Swagger API definition is bound.
|String
|`openapi.context.id.default`

|holon.swagger.*resource-package*
|The package names to use to filter the API resource classes to be included in the Swagger API definition. More than one package name can be specified using a comma (`,`) as separator.
|String
|_None_

|holon.swagger.*include-all*
|Whether to include all the available API resource classes in the Swagger API definition. If `false`, only the `io.swagger.annotations.Api` annotated resource classes will be incuded for Swagger V2 or only the `io.swagger.v3.oas.annotations.Operation` annotated resource methods will be included for Swagger V3.
|Boolean
|`true`

|holon.swagger.*ignored-routes*
|A comma separated list of API operation routes to be ignored for the Swagger API definition generation.
|String
|_None_

|holon.swagger.*pretty-print*
|Whether _pretty_ format the Swagger API definition output provided by the API definition endpoints.
|Boolean
|`false`

|holon.swagger.*v2.path*
|Specific API definition endpoint JAX-RS path for Swagger API specification version 2. Overrides the default `holon.swagger.path` when the Swagger V2 integration is available from classpath. See <<V2andV3>>.
|String
|_None_

|holon.swagger.*v3.path*
|Specific API definition endpoint JAX-RS path for Swagger/OpenAPI specification version 3. Overrides the default `holon.swagger.path` when the Swagger V3 integration is available from classpath. See <<V2andV3>>.
|String
|_None_

|===

*3. API definition configuration:*

|===
|Property name |Type |Meaning |Default

|holon.swagger.*title*
|The API definition title.
|String
|_None_

|holon.swagger.*version*
|The API definition version.
|String
|_None_

|holon.swagger.*description*
|The API definition description.
|String
|_None_

|holon.swagger.*terms-of-service-url*
|The API definition terms of service URL.
|String
|_None_

|holon.swagger.*contact.name*
|The API definition contact name.
|String
|_None_

|holon.swagger.*contact.email*
|The API definition contact email.
|String
|_None_

|holon.swagger.*contact.url*
|The API definition contact URL.
|String
|_None_

|holon.swagger.*license.name*
|The API definition license name.
|String
|_None_

|holon.swagger.*license.url*
|The API definition license URL.
|String
|_None_

|holon.swagger.*external-docs.url*
|The API definition external documentation URL.
|String
|_None_

|holon.swagger.*external-docs.description*
|The API definition external documentation description.
|String
|_None_

|holon.swagger.*server.url*
|The API definition server URL.
|String
|_None_

|holon.swagger.*server.description*
|The API definition server description.
|String
|_None_

|holon.swagger.*security*
|The API security requirements definition. See the example below.
|A List of (String, List<String>) pairs
|_None_

|===

*4. Deprecated API definition properties*, from version 5.2.x:

|===
|Property name |Meaning |Replaced by

|holon.swagger.*license-url*
|The API definition license URL.
|holon.swagger.license.url

|holon.swagger.*schemes*
|The API definition server schemes.
|holon.swagger.server.url

|holon.swagger.*host*
|The API definition server host.
|holon.swagger.server.url

|===

Example:

.application.yml
[source, yaml]
----
holon:
  swagger:
    title: 'My title'
    version: 'v1'
    path: 'docs'
    type: PATH_PARAMETER
    scanner-type: APPLICATION_AND_ANNOTATION
    pretty-print: true
    security:
      - name: 'requirement 1'
        value: 'value1'
      - name: 'requirement 2'
        value: 'value2,value3'
----

In the example above the Swagger API definition endpoint will be mapped to the `docs` path. The Swagger API definition endpoint will be of `PATH_PARAMETER` type and the API resources scan strategy to use is setted to `APPLICATION_AND_ANNOTATION`.

[[BeanConfiguration]]
==== API and endpoints configuration using beans

Besides the <<PropertiesConfiguration>>, the API endpoints and the API definition can be configured using an appropriate configuration class, declared as a *Spring bean* in the application context.

The required configuration bean type depends on the Swagger API specification version:

* For Swagger API specification *version 2*: A `io.swagger.config.SwaggerConfig` bean type is required.
* For Swagger/OpenAPI specification *version 3*: A `io.swagger.v3.oas.integration.api.OpenAPIConfiguration` bean type is required.

IMPORTANT: When a suitable API configuration bean is available in the application context, it will be used for API definition endpoints auto-configuration and *any `holon.swagger.*` configuration property will be ignored*.

.Swagger V2
[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=beanconfig1,indent=0]
----

.Swagger V3
[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=beanconfig2,indent=0]
----

For what concern the API definition endpoint, the link:{apidir}/com/holonplatform/jaxrs/swagger/annotations/ApiConfiguration.html[ApiConfiguration^] annotation can be used on the configuration bean classes.

The `@ApiConfiguration` annotation allows to configure:

* The API *context id* to which the API definition endpoint is bound, using the `contextId` attribute.
* The JAX-RS *path* to which the API definition endpoint is mapped, using the `path` attribute.
* The API definition *endpoint type*, using the `endpointType` attribute. See <<ApiEndpointType>>.
* The *scanner type* to use to detect the API resource classes, using the `scannerType` attribute. See <<JaxrsScannerType>>.

.Swagger V2 with ApiConfiguration annotation
[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=beanconfig3,indent=0]
----

.Swagger V3 with ApiConfiguration annotation
[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=beanconfig4,indent=0]
----

More than one API configuration bean can be declared to register multiple Swagger API definition endpoints, see <<MultipleEnpoints>>.

Swagger API specification version 2 and 3 type configuration beans can coexist in the same application context: see <<V2andV3>>.

[[MultipleEnpoints]]
==== Multiple API endpoints configuration

More than one Swagger API definition endpoint can be configured for the same application. This can be typically used to provide an API definition for a *different API resources subset* for each endpoint.

IMPORTANT: Each API definition endpoint registered in the same application must be mapped to a *different JAX-RS path*.

In this scenario, the default JAX-RS path (`api-docs`) cannot be used for every API definition endpoint when more than one is registered to avoid path conflicts.

The API definition endpoint JAX-RS path can be declared using the `holon.swagger.path` configuration property (see <<PropertiesConfiguration>>) or the `path` attribute of the `@ApiConfiguration` annotation, if a bean based configuration is used (see <<BeanConfiguration>>).

See below to learn how to group the API resource classes to create different API definition subsets.

[[ResourcePackages]]
===== Using a package prefix to group the API resources

When a *package prefix* is used to group the API resources, each API definition group will contain the API resource classes which package name starts with the specified package prefix.

The package prefix can be specified either using a API configuration bean or using the `holon.swagger.api-groups` configuration property.

*1. Bean based API configuration:* 

One or more package prefix can be configured using a Swagger API configuration bean. See <<BeanConfiguration>> for information about the bean class to use for Swagger API definition version 2 or version 3.

The `@ApiConfiguration` annotation can be used on each API configuration bean to specify the API definition endpoint JAX-RS *path*.

.Swagger V2 API groups configuration
[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=multi1,indent=0]
----
<1> API group 1 configuration: will include the API resource classes which package name starts with the `my.resource.package.group1` package name. The API definition endpoint is mapped to the `docs1` path.
<2> API group 2 configuration: will include the API resource classes which package name starts with the `my.resource.package.group2` package name. The API definition endpoint is mapped to the `docs2` path. 

.Swagger V3 API groups configuration
[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=multi2,indent=0]
----
<1> API group 1 configuration: will include the API resource classes which package name starts with the `my.resource.package.group1` package name. The API definition endpoint is mapped to the `docs1` path.
<2> API group 2 configuration: will include the API resource classes which package name starts with the `my.resource.package.group2` package name. The API definition endpoint is mapped to the `docs2` path. 

*1. Application properties based API configuration:*

When the Spring Boot application configuration properties are used for Swagger API definition endpoints configuration, the `holon.swagger.api-groups` configuration property can be used to declare a set of API definition groups.

Each group should provide a *group id* (which will be used as API definition context id) and an optional set of API definition and API endpoint configuration properties. The available configuration properties for each group are the same of the default Swagger configuration property set. See <<PropertiesConfiguration>>.

The package prefix to use for each API definition group can be specified using the `resource-package` configuration property. The property allows to specify more than one package prefix for each group, using a comma (`,`) as separator.

For example, given the following configuration:

.application.yml
[source, yaml]
----
holon:
  swagger:
    api-groups:
      - group-id: 'group1'
        title: 'API group 1'
        resource-package: 'my.resource.package.group1'
        path: 'docs1'
      - group-id: 'group2'
        title: 'API group 2'
        resource-package: 'my.resource.package.group2'
        path: 'docs2'
----

Two API definition endpoints will be configured:

* One for the `group1` API definition with title _API group 1_, including the API resource classes which package name starts with the `my.resource.package.group1` package name, mapped to the `docs1` path.
* And one for the `group2` API definition with title _API group 2_, including the API resource classes which package name starts with the `my.resource.package.group2` package name, mapped to the `docs2` path.

The _root level_ API configuration properties are *inherited by each API group definition*, if the corresponding property is not explicitly specified in the group property set.

For example, given the following configuration:

.application.yml
[source, yaml]
----
holon:
  swagger:
    version: 'v1'
    api-groups:
      - group-id: 'group1'
        title: 'API group 1'
        resource-package: 'my.resource.package.group1'
        path: 'docs1'
      - group-id: 'group2'
        title: 'API group 2'
        resource-package: 'my.resource.package.group2'
        path: 'docs2'
----

The `version` property value (`v1`) will be inherited by both the group 1 and group 2 API definition. 

[[ApiContextId]]
===== Using the `ApiContextId` annotation to group the API resources

TBD


[[V2andV3]]
=== Enabling Swagger V2 and V3 API endpoints simultaneously

TBD

=== Disabling the Swagger API endpoints auto-configuration

TBD

=== ApiDefinition annotation deprecation

TBD 

