[[Swagger]]
== Swagger / OpenAPI integration

_Swagger V2 Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-swagger-v2</artifactId>
<version>{revnumber}</version>
----

_Swagger/OpenAPI V3 Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-swagger-v3</artifactId>
<version>{revnumber}</version>
----

The `holon-jaxrs-swagger-v2` and `holon-jaxrs-swagger-v3` provides integration with the  link:http://swagger.io[Swagger^] _OpenAPI Specification_, for the *Swagger Version 2* and the *Swagger/OpenAPI Version 3* specifications respectively.

The integration facilities concerns the following aspects:

* A complete integration with the Holon Platform *Property model* data types, specifically with the link:holon-core.html#PropertyBox[PropertyBox] type, ensuring a consistent representation and serialization using the Swagger/OpenAPI definition models.

* A convenient `ApiReader` API to obtain a Swagger/OpenAPI definition from a set of API resource classes.

* A complete and highly configurable *Spring Boot* integration, with auto-configuration facilities for both *Jersey* and *Resteasy* JAX-RS runtimes.

TIP: The Swagger/OpenAPI integration architecture is designed to be highly consistent between the Swagger/OpenAPI versions 2 and 3, so in most cases it is enough to put the `holon-jaxrs-swagger-v2` or the `holon-jaxrs-swagger-v3` artifact in classpath to enable the integration features. Or even both: see <<V2andV3>>.

=== `PropertyBox` data type support

When the `holon-jaxrs-swagger-v2` or the `holon-jaxrs-swagger-v3` artifact is in classpath, the Swagger/OpenAPI reader engine is automatically configured to support the `PropertyBox` type as API operations parameter or return type.

IMPORTANT: If you programmatically use the Swagger/OpenAPI reader or context configuration classes to generate the API definition model, you have to include a proper `ReaderListener` class in the API resource classes to ensure a consistent `PropertyBox` type handling. This class is available from the `CONTEXT_READER_LISTENER` static attribute of the  
link:{apidir}/com/holonplatform/jaxrs/swagger/v2/SwaggerV2.html[SwaggerV2^] interface for the Swagger V2 integration and of the link:{apidir}/com/holonplatform/jaxrs/swagger/v3/SwaggerV3.html[SwaggerV3^] interface for the Swagger/OpenAPI V3 integration.

TIP: When the <<SwaggerSpringBoot,Spring Boot integration>> is enabled or an <<ApiReader,ApiReader>> is used, the Swagger/OpenAPI engine is automatically configured for a consistent `PropertyBox` type support.

==== `PropertyBox` property set decalration

A `PropertyBox` type API parameter or return type is translated in a regular Swagger _object_ definition, listing all the properties of the `PropertyBox` *property set*.

NOTE: By default, only the `Path` type properties are included in the API definition _models_/_schemas_, using the `Path` *name* as model/schema attribute name and the property *type* as model/schema attribute type.

Since a `PropertyBox` type class does not provide a fixed link:holon-core.html#PropertySet[PropertySet] decalration, the link:{coreapidir}/com/holonplatform/core/property/PropertySetRef.html[PropertySetRef^] *annotation has to be used* to declare the `PropertySet` to use to translate the `PropertyBox` type into an API model/schema definition. The annotation has to be placed on the `PropertyBox` type method parameters and/or method return types.

The `PropertySetRef` annotation *value* can be either:
* A class which contains the `PropertySet` instance as a `public static` field.
* A `PropertySet` type class: in this case, a new instance of such class will be used.

When the first option is used and more than one `PropertySet` type static field is available in the provided class, the *field* annotation attribute can be used to specify the field name to use.

TBD: examples

==== Creating a Swagger Model/Schema definition for a `PropertyBox` type

TBD

To create a regular Swagger *Model definition*, listed in the _definitions_ section of the Swagger specification and referenced by name by API definitions, the link:{apidir}/com/holonplatform/jaxrs/swagger/annotations/ApiPropertySetModel.html[ApiPropertySetModel^] annotation can be used in conjuction with the `@PropertySetRef` annotation, using the annotation `value()` attribute to declare the model definition *name* to generate for a `PropertyBox` type object.

[[ApiReader]]
=== Using the `ApiReader` to generate the API definition model

TBD

[[SwaggerSpringBoot]]
=== Spring Boot integration

The `holon-jaxrs-swagger` provides Spring Boot auto-configuration classes to automatically configure *Swagger API listing JAX-RS endpoints* in a Spring Boot application.

The Swagger auto-configuration is triggered when either a `ResourceConfig` type _Jersey_ configuration bean or a `ResteasyConfig` type _Resteasy_ configuration bean is available in Spring context.

==== Swagger API documentation endpoints configuration using properties

The Swagger auto-configuration relies on the `holon.swagger.*` configuration properties listed in the link:{apidir}/com/holonplatform/jaxrs/swagger/spring/SwaggerConfigurationProperties.html[SwaggerConfigurationProperties^] class to configure the Swagger API endpoints.

TIP: Just like any other Spring Boot configuration property, the `holon.swagger.*` properties can be specified in your inside your `application.properties` / `application.yml` file or as command line switches.

At least the `holon.swagger.resource-package` property, which specifies the Java _package_ name to scan to detect the JAX-RS API endpoints, must be setted to auto-configure a Swagger API listing endpoint. See <<SwaggerConfigurationProperties>> for a list of all available configuration properties.

By default, the `/api-docs` default path is used to expose the API listing endpoint, but can be changed using the `holon.swagger.path` property.

The API listing endpoint supports the `type` query parameter name to obtain the Swagger API definitions either in *JSON*, using the `json` parameter value (the default format), or in *YAML*, using the `yaml` parameter value.

For example, for a configuration like the following:

.application.yml
[source, yaml]
----
holon:
  swagger:
    version: "v1"
    title: "Test Swagger API"
    resource-package: "my.api.endpoints"
    path: "docs"
    pretty-print: true
----

The `my.api.endpoints` package is scanned to detect JAX-RS API resources and the API listing endpoint will be available at the `http(s):host/docs` URL.

===== Configure multiple API listing endpoints

Multiple API listing endpoints configuration is supported using the `holon.swagger.api-groups` configuration property, which accept a list of API _groups_, each bound to a specific API _package_ to scan and which can be independently configured using the <<SwaggerConfigurationProperties>>.

For each API group, an API listing endpoint will be available at the base API listing path (`/api-docs` by default, or the one configured with the `holon.swagger.path` property at the root level) followed by the `group-id` property name. For example: `http(s):host/api-docs/one`.

If a `group-id` is not specified, the `default` group id will be used and the API listing endpoint will be available at the base API listing path.

For example, for a configuration like the following:

.application.yml
[source, yaml]
----
holon:
  swagger:
    version: "v1"
    title: "Test Swagger API"
    
    api-groups:
      - group-id: "one" 
        resource-package: "my.api.endpoints.one"
        description: "The API group 1"
        path: docs/one
      - group-id: "two"
        resource-package: "my.api.endpoints.two"
        description: "The API group 2"
        path: docs/two
----

Two API groups are defined:

* The group 1, bound to the `my.api.endpoints.one` package and for which the API listing endpoint will be available at the `http(s):host/docs/one` URL.
* The group 2, bound to the `my.api.endpoints.two` package and for which the API listing endpoint will be available at the `http(s):host/docs/two` URL.

[[SwaggerConfigurationProperties]]
==== Swagger configuration properties

.Common configuration properties
|===
|Name |Meaning

|_holon.swagger._ *enabled*
|Whether the Swagger API listing endpoints auto-configuration is enabled. Default is `true`.

|_holon.swagger._ *resourcePackage*
|The package name to scan to detect API endpoints

|_holon.swagger._ *path*
|API listing endpoint path. When at group level, is appended to the base API listing path.

|_holon.swagger._ *schemes*
|API supported protocol schemes list (`http`, `https`)

|_holon.swagger._ *title*
|API title

|_holon.swagger._ *version*
|API version

|_holon.swagger._ *description*
|API description

|_holon.swagger._ *termsOfServiceUrl*
|Terms of Service URL

|_holon.swagger._ *contact*
|Contact information

|_holon.swagger._ *license*
|License information

|_holon.swagger._ *licenseUrl*
|License URL

|_holon.swagger._ *host*
|API host name

|_holon.swagger._ *pretty-print*
|Whether to _pretty_ format API listing output (`true` or `false`)

|_holon.swagger._ *api-groups*
|Optional API groups. Each group can be configured using the properties listed below.
|===

.API group configuration properties
|===
|Name |Meaning

|_holon.swagger.api-groups._ *group-id*
|API group id, also used as API listing endpoint sub-path is group `path` is not specified

|_holon.swagger.api-groups._ *resourcePackage*
|The package name to scan to detect API group endpoints

|_holon.swagger.api-groups._ *path*
|API group listing endpoint path

|_holon.swagger.api-groups._ *schemes*
|API group supported protocol schemes list (`http`, `https`)

|_holon.swagger.api-groups._ *title*
|API group title

|_holon.swagger.api-groups._ *version*
|API group version

|_holon.swagger.api-groups._ *description*
|API group description

|_holon.swagger.api-groups._ *termsOfServiceUrl*
|Terms of Service URL

|_holon.swagger.api-groups._ *contact*
|Contact information

|_holon.swagger.api-groups._ *license*
|License information

|_holon.swagger.api-groups._ *licenseUrl*
|License URL
|===

[[SwaggerAPIEndpointAutoConfiguration]]
==== Swagger API documentation endpoints auto-configuration

If the `holon.swagger.resourcePackage` configuration property is not provided and no API groups are defined using the `holon.swagger.apiGroups.*` configuration properties, the Holon Swagger integration module will try to auto-configure the Swagger API listing endpoints, relying on the Swagger `@Api` annotation.

IMPORTANT: Any JAX-RS `@Path` resource declared as a Spring bean which is annotated with the Swagger `@Api` annotation will be auto-detected and used to obtain the package name to use as Swagger API listing endpoint source.

The default `/api-docs` path is used as the Swagger API listing mapping.

To configure the API listing path and the API information properties, the link:{apidir}/com/holonplatform/jaxrs/swagger/annotations/ApiDefinition.html[ApiDefinition^] annotation can be used. The `@ApiDefinition` annotation can be used at package level (annotating a standard `package-info.java` class) or at resource class level.

The `@ApiDefinition` allows to setup the Swagger API documentation general informations, providing attributes to set the same information which can be configured using the <<SwaggerConfigurationProperties>> property set.

For example, given the following endpoint class:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=swagger1,indent=0]
----
<1> Standard Swagger `@Api` annotation to scan and include the endopoint class in the API documentation
<2> The API documentation _title_ is defined using the `@ApiDefinition` annotation
<3> Declare the endpoint as a Spring bean
<3> Standard Swagger annotations for the API documentation generation.

A Swagger API listing endpoint will be automatic configured and mapped to the default JAX-RS path: `/api-docs`.

To provide a different API listing endpoint mapping path, the `@ApiDefinition` annotation `value` can be used:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=swagger2,indent=0]
----
<1> Map the Swagger API listing endpoint to the `/docs` path

===== Multiple JAX-RS endpoint resources auto-configuration

When more than one JAX-RS endpoint is auto-configured for Swagger API documentation, you must pay attention to the declared Swagger API listing endpoint **paths** declared using the `@ApiDefinition` annotation.

All the JAX-RS endpoint classes bound to the same Swagger API documentation **path** will be merged into a **single Swagger API documentation configuration**. The API documentation configuration properties, if any, will be obtained form the available `@ApiDefinition` annotations which refer to the same path.

WARNING: When the `@ApiDefinition` annotations attributes declared for the same path are not consistent, a configuration exception will be thrown at application startup. For example, if two JAX-RS endpoint classes are annotated with `@ApiDefinition(value="/docs", title = "Title1")` and `@ApiDefinition(value="/docs", title = "Title2")` a configuration exception will be thrown, since a unique API title for the path `/docs` cannot be determined.

For example, given the following JAX-RS endpoints:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=swagger3,indent=0]
----
<1> Set the API listing path to `/docs1` and the API title to `Title 1`
<2> Set the API listing path to `/docs1`
<3> Set the API listing path to `/docs2` and the API title to `Title 2`

Two Swagger API listing endpoints will be auto-configured:

* One mapped to the `/docs1` path, which will provide the documentation for both `ExampleEndpoint3a` and `ExampleEndpoint3b` operations. The configured API title will be `Title 1`.

* Another mapped to the `/docs2` path, which will only provide the documentation for the `ExampleEndpoint3c` operations. The configured API title will be `Title 2`.

[[V2andV3]]
=== Enabling Swagger V2 and V3 API endpoints simultaneously

TBD
