[[Swagger]]
== Swagger integration

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-swagger</artifactId>
<version>{revnumber}</version>
----

This artifact provides a complete integration with link:http://swagger.io[Swagger^] _OpenAPI Specification_, to configure API listing JAX-RS endpoints and to handle the `PropertyBox` data container type as a Swagger _Model_ definition.

=== `PropertyBox` support

When the `holon-jaxrs-swagger` artifact is in classpath, the Swagger JAX-RS engine is automatically configured to support the `PropertyBox` type as API parameter or return type, but to ensure a proper `PropertyBox` handling the internal _SwaggerContext_ must be setted up. This can be done either by:

* Using the link:{apidir}/com/holonplatform/jaxrs/swagger/SwaggerConfiguration.html[SwaggerConfiguration^] Swagger `BeanConfig` extension class, instead of the standard `BeanConfig` class
* Or providing the link:{apidir}/com/holonplatform/jaxrs/swagger/SwaggerContextListener.html[SwaggerContextListener^] Swagger `ReaderListener` class as a Swagger scanned resource class

=== `PropertyBox` model definition

A `PropertyBox` type API parameter or return type is translated in a regular Swagger _object_ definition, listing all the *properties* of the `PropertyBox` property-set which implement the `Path` interface, using the `Path` name as _object_ attribute name and the property type (adapted to a standard JSON type) as attribute type.

The `x-holon-model-type` extension property is added to each Swagger `PropertyBox` type object definition, with the `com.holonplatform.core.property.PropertyBox` value.

The link:{coreapidir}/com/holonplatform/core/property/PropertySetRef.html[PropertySetRef^] annotation has to be used in JAX-RS resource methods for `PropertyBox` type parameters or return types to declare the *property set* to be used to serialize a `PropertyBox` declaration.

To create a regular Swagger *Model definition*, listed in the _definitions_ section of the Swagger specification and referenced by name by API definitions, the link:{apidir}/com/holonplatform/jaxrs/swagger/annotations/ApiPropertySetModel.html[ApiPropertySetModel^] annotation can be used in conjuction with the `@PropertySetRef` annotation, using the annotation `value()` attribute to declare the model definition *name* to generate for a `PropertyBox` type object.

CAUTION: Ensure to assign the same model name to `PropertyBox` type parameters and return types which are meant to be used with the same property set and to declare different model names for different property sets.

=== Spring Boot integration

The `holon-jaxrs-swagger` provides Spring Boot auto-configuration classes to automatically configure *Swagger API listing JAX-RS endpoints* in a Spring Boot application.

The Swagger auto-configuration is triggered when either a `ResourceConfig` type _Jersey_ configuration bean or a `ResteasyConfig` type _Resteasy_ configuration bean is available in Spring context.

==== Swagger API documentation endpoints configuration using properties

The Swagger auto-configuration relies on the `holon.swagger.*` configuration properties listed in the link:{apidir}/com/holonplatform/jaxrs/swagger/spring/SwaggerConfigurationProperties.html[SwaggerConfigurationProperties^] class to configure the Swagger API endpoints.

TIP: Just like any other Spring Boot configuration property, the `holon.swagger.*` properties can be specified in your inside your `application.properties` / `application.yml` file or as command line switches.

At least the `holon.swagger.resource-package` property, which specifies the Java _package_ name to scan to detect the JAX-RS API endpoints, must be setted to auto-configure a Swagger API listing endpoint. See <<SwaggerConfigurationProperties>> for a list of all available configuration properties.

By default, the `/api-docs` default path is used to expose the API listing endpoint, but can be changed using the `holon.swagger.path` property.

The API listing endpoint supports the `type` query parameter name to obtain the Swagger API definitions either in *JSON*, using the `json` parameter value (the default format), or in *YAML*, using the `yaml` parameter value.

For example, for a configuration like the following:

.application.yml
[source, yaml]
----
holon:
  swagger:
    version: "v1"
    title: "Test Swagger API"
    resource-package: "my.api.endpoints"
    path: "docs"
    pretty-print: true
----

The `my.api.endpoints` package is scanned to detect JAX-RS API resources and the API listing endpoint will be available at the `http(s):host/docs` URL.

===== Configure multiple API listing endpoints

Multiple API listing endpoints configuration is supported using the `holon.swagger.api-groups` configuration property, which accept a list of API _groups_, each bound to a specific API _package_ to scan and which can be independently configured using the <<SwaggerConfigurationProperties>>.

For each API group, an API listing endpoint will be available at the base API listing path (`/api-docs` by default, or the one configured with the `holon.swagger.path` property at the root level) followed by the `group-id` property name. For example: `http(s):host/api-docs/one`.

If a `group-id` is not specified, the `default` group id will be used and the API listing endpoint will be available at the base API listing path.

For example, for a configuration like the following:

.application.yml
[source, yaml]
----
holon:
  swagger:
    version: "v1"
    title: "Test Swagger API"
    
    api-groups:
      - group-id: "one" 
        resource-package: "my.api.endpoints.one"
        description: "The API group 1"
        path: docs/one
      - group-id: "two"
        resource-package: "my.api.endpoints.two"
        description: "The API group 2"
        path: docs/two
----

Two API groups are defined:

* The group 1, bound to the `my.api.endpoints.one` package and for which the API listing endpoint will be available at the `http(s):host/docs/one` URL.
* The group 2, bound to the `my.api.endpoints.two` package and for which the API listing endpoint will be available at the `http(s):host/docs/two` URL.

[[SwaggerConfigurationProperties]]
==== Swagger configuration properties

.Common configuration properties
|===
|Name |Meaning

|_holon.swagger._ *enabled*
|Whether the Swagger API listing endpoints auto-configuration is enabled. Default is `true`.

|_holon.swagger._ *resourcePackage*
|The package name to scan to detect API endpoints

|_holon.swagger._ *path*
|API listing endpoint path. When at group level, is appended to the base API listing path.

|_holon.swagger._ *schemes*
|API supported protocol schemes list (`http`, `https`)

|_holon.swagger._ *title*
|API title

|_holon.swagger._ *version*
|API version

|_holon.swagger._ *description*
|API description

|_holon.swagger._ *termsOfServiceUrl*
|Terms of Service URL

|_holon.swagger._ *contact*
|Contact information

|_holon.swagger._ *license*
|License information

|_holon.swagger._ *licenseUrl*
|License URL

|_holon.swagger._ *host*
|API host name

|_holon.swagger._ *pretty-print*
|Whether to _pretty_ format API listing output (`true` or `false`)

|_holon.swagger._ *auth-schemes*
|Enable authentication for the API listing endpoints using the `@Authenticate` annotation behaviour, specifying the allowed authentication schemes. If only one scheme with the `*` value is provided, any supported authentication scheme is allowed for authentication.

|_holon.swagger._ *security-roles*
|A list of security roles for API listing access control using the JAX-RS `SecurityContext` and the `@RolesAllowed` annotation

|_holon.swagger._ *api-groups*
|Optional API groups. Each group can be configured using the properties listed below.
|===

.API group configuration properties
|===
|Name |Meaning

|_holon.swagger.api-groups._ *group-id*
|API group id, also used as API listing endpoint sub-path is group `path` is not specified

|_holon.swagger.api-groups._ *resourcePackage*
|The package name to scan to detect API group endpoints

|_holon.swagger.api-groups._ *path*
|API group listing endpoint path

|_holon.swagger.api-groups._ *schemes*
|API group supported protocol schemes list (`http`, `https`)

|_holon.swagger.api-groups._ *title*
|API group title

|_holon.swagger.api-groups._ *version*
|API group version

|_holon.swagger.api-groups._ *description*
|API group description

|_holon.swagger.api-groups._ *termsOfServiceUrl*
|Terms of Service URL

|_holon.swagger.api-groups._ *contact*
|Contact information

|_holon.swagger.api-groups._ *license*
|License information

|_holon.swagger.api-groups._ *licenseUrl*
|License URL

|_holon.swagger.api-groups._ *auth-schemes*
|Enable authentication for the API group listing using the `@Authenticate` annotation behaviour, specifying the allowed authentication schemes. If only one scheme with the `*` value is provided, any supported authentication scheme is allowed for authentication.

|_holon.swagger.api-groups._ *security-roles*
|A list of security roles for API group listing access control using the JAX-RS `SecurityContext` and the `@RolesAllowed` annotation
|===

==== Swagger API documentation endpoints auto-configuration

If the `holon.swagger.resourcePackage` configuration property is not provided and no API groups are defined using the `holon.swagger.apiGroups.*` configuration properties, the Holon Swagger integration module will try to auto-configure the Swagger API listing endpoints, relying on the Swagger `@Api` annotation.

Any JAX-RS `@Path` resource declared as a Spring bean which is annotated with the Swagger `@Api` annotation will be auto-detected and used to obtain the package name to use as Swagger API listing endpoint source.

The default `/api-docs` path is used as the Swagger API listing mapping.

To configure the API listing path and the API information properties, the link:{apidir}/com/holonplatform/jaxrs/swagger/annotations/ApiDefinition.html[ApiDefinition^] annotation can be used. The `@ApiDefinition` annotation can be used at package level (annotating a standard `package-info.java` class) or at resource class level, when a single JAX-RS `@Api` resource class is present.

When more than one package which contains valid JAX-RS `@Api` classes is present, the Swagger API listings path must be different for each package, so the `@ApiDefinition` annotation is required to specify the API documentation path for each package.
