[[Swagger]]
== Swagger / OpenAPI integration

_Swagger V2 Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-swagger-v2</artifactId>
<version>{revnumber}</version>
----

_Swagger/OpenAPI V3 Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-swagger-v3</artifactId>
<version>{revnumber}</version>
----

The `holon-jaxrs-swagger-v2` and `holon-jaxrs-swagger-v3` provides integration with the  link:http://swagger.io[Swagger^] _OpenAPI Specification_, for the *Swagger Version 2* and the *Swagger/OpenAPI Version 3* specifications respectively.

WARNING: The Holon Platform 5.1.x `holon-jaxrs-swagger` artifact is *deprecated* and should be replaced with the `holon-jaxrs-swagger-v2` artifact. The `holon-jaxrs-swagger` is still available in Holon Platform version 5.2.x, acting as an alias only for backward compatibility purposes.

The integration facilities concerns the following aspects:

* A complete integration with the Holon Platform *Property model* data types, specifically with the link:holon-core.html#PropertyBox[PropertyBox] type, ensuring a consistent representation and serialization using the Swagger/OpenAPI definition models.

* A convenient `ApiReader` API to obtain a Swagger/OpenAPI definition from a set of API resource classes.

* A complete and highly configurable *Spring Boot* integration, with auto-configuration facilities for both *Jersey* and *Resteasy* JAX-RS runtimes.

TIP: The Swagger/OpenAPI integration architecture is designed to be highly consistent between the Swagger/OpenAPI versions 2 and 3, so in most cases it is enough to put the `holon-jaxrs-swagger-v2` or the `holon-jaxrs-swagger-v3` artifact in classpath to enable the integration features. Or even both: see <<V2andV3>>.

=== `PropertyBox` data type support

When the `holon-jaxrs-swagger-v2` or the `holon-jaxrs-swagger-v3` artifact is in classpath, the Swagger/OpenAPI reader engine is automatically configured to support the `PropertyBox` type as API operations parameter or return type.

IMPORTANT: If you programmatically use the Swagger/OpenAPI reader or context configuration classes to generate the API definition model, you have to include a proper `ReaderListener` class in the API resource classes to ensure a consistent `PropertyBox` type handling. This class is available from the `CONTEXT_READER_LISTENER` static attribute of the  
link:{apidir}/com/holonplatform/jaxrs/swagger/v2/SwaggerV2.html[SwaggerV2^] interface for the Swagger V2 integration and of the link:{apidir}/com/holonplatform/jaxrs/swagger/v3/SwaggerV3.html[SwaggerV3^] interface for the Swagger/OpenAPI V3 integration.

TIP: When the <<SwaggerSpringBoot,Spring Boot integration>> is enabled or an <<ApiReader,ApiReader>> is used, the Swagger/OpenAPI engine is automatically configured for a consistent `PropertyBox` type support.

[[PropertySetRef]]
==== `PropertyBox` property set declaration

A `PropertyBox` type API parameter or return type is translated in a regular Swagger/OpenAPI _object_ type Model/Schema definition, listing all the properties of the `PropertyBox` *property set* as object attributes.

NOTE: By default, only the `Path` type properties are included in the API definition _models_/_schemas_, using the `Path` *name* as model/schema attribute name and the property *type* as model/schema attribute type.

Since a `PropertyBox` type class does not provide a fixed link:holon-core.html#PropertySet[PropertySet] decalration, the link:{coreapidir}/com/holonplatform/core/property/PropertySetRef.html[PropertySetRef^] *annotation has to be used* to declare the `PropertySet` to use to translate the `PropertyBox` type into an API model/schema definition. The annotation has to be placed on the `PropertyBox` type method parameters and/or method return types.

The `PropertySetRef` annotation *value* can be either:
* A class which contains the `PropertySet` instance as a `public static` field.
* A `PropertySet` type class: in this case, a new instance of such class will be used.

When the first option is used and more than one `PropertySet` type static field is available in the provided class, the *field* annotation attribute can be used to specify the field name to use.

[[Subjects]]
For example, given the following `SubjectModel` interface, which contains a data model declaration for a simple subject entity:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=model,indent=0]
----
<1> `PropertySet` definition

The `SUBJECT` field can be used as `PropertyBox` property set definition in a JAX-RS API endpoint like this:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=propertyset,indent=0]
----
<1> Declare the `PropertySet` to use for the `getById` operation *return type*, using the `PropertySetRef` annotation
<2> Declare the `PropertySet` to use for the `create` operation *body parameter*, using the `PropertySetRef` annotation

Since the `SUBJECT` field is the unique `PropertySet` type static field of the `SubjectModel` interface, no additional *field* name specification is required in the `PropertySetRef` annotation.

In this example, the generated API definition will look like this (using the YAML format):

.Swagger 2 specification:
[source, yaml]
----
swagger: "2.0"
paths:
  /subjects/{id}:
    get:
      operationId: "getById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          headers: {}
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int32"
              name:
                type: "string"
            title: "PropertyBox"
  /subjects:
    put:
      operationId: "create"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "object"
          properties:
            id:
              type: "integer"
              format: "int32"
            name:
              type: "string"
          title: "PropertyBox"
      responses:
        default:
          description: "successful operation"
definitions: {}
----

.Swagger/OpenAPI 3 specification:
[source, yaml]
----
openapi: 3.0.1
paths:
  /subjects/{id}:
    get:
      operationId: getById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                title: PropertyBox
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
  /subjects:
    put:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              title: PropertyBox
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
      responses:
        default:
          description: default response
          content:
            '*/*': {}
components:
  schemas: {}
----

See the next section to learn how to include a `PropertyBox` type model/schema in the Swagger API definition `definitions` (for Swagger V2) or `components/schemas` (for Swagger V3).

==== Creating a Swagger Model/Schema definition for a `PropertyBox` type

When the `PropertySetRef` annotation is used, a generic Swagger _object_ type model/schema definition is generated for each API response or API operation parameter, using the property set definition to generate the schema properties.

To include a `PropertyBox` type as a _named_ model/schema in the Swagger API definition (i.e. to create a type declaration in the `definitions` section for Swagger V2 or in the `components/schemas` section for Swagger V3), the link:{apidir}/com/holonplatform/jaxrs/swagger/annotations/ApiPropertySetModel.html[ApiPropertySetModel^] annotation can be used.

The `ApiPropertySetModel` *value* attribute is used to specify the model/schema _name_. When a `PropertyBox` type model is declared this way, its name will be used as a _reference_ in the API operation components which use it.

The `ApiPropertySetModel` annotation should be always used in conjunction with the `PropertySetRef` annotation, which provides the property set declaration.

TIP: To make the API enpoints code more readable and to ensure a consistent property set and model name definition, the `PropertySetRef` and `ApiPropertySetModel` annotations can be used as meta-annotations to create specific annotations to be used in the API endpoints code. See below for an example.

Taking the <<Subjects,Subjects>> example endpoint declaration, we can create a `Subject` annotation to declare the `PropertySet` to use and a model/schema definition named `Subject` this way:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=apimodel1,indent=0]
----
<1> `PropertySet` reference declaration
<2> Model/Schema *name* definition

Next, the `Subject` annotation is used in the JAX-RS endpoint instead of the simple `PropertySetRef` annotation:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=apimodel2,indent=0]
----
<1> Declare the `Subject` model definition for the `getById` operation *return type*
<2> Declare the `Subject` model definition for the `create` operation *body parameter*

The generated API definition will include a `Subject` model/schema definition and will look like this:

.Swagger 2 specification:
[source, yaml]
----
swagger: "2.0"
paths:
  /subjects/{id}:
    get:
      operationId: "getById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          headers: {}
          schema:
            $ref: "#/definitions/Subject"
  /subjects:
    put:
      operationId: "create"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Subject"
      responses:
        default:
          description: "successful operation"
definitions:
  Subject:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
    title: "Subject"
----

.Swagger/OpenAPI 3 specification:
[source, yaml]
----
openapi: 3.0.1
paths:
  /subjects/{id}:
    get:
      operationId: getById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
  /subjects:
    put:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
      responses:
        default:
          description: default response
          content:
            '*/*': {}
components:
  schemas:
    Subject:
      title: Subject
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
----

In the API definition, the API operation return types or body parameters annotated with the `Subject` annotation declarations provide a *reference* to the `Subject` model/schema definition.

[[ApiReader]]
=== Using the `ApiReader` to generate the API definition model

The link:{apidir}/com/holonplatform/jaxrs/swagger/ApiReader.html[ApiReader^] service can be used to directly generate a Swagger API definition model from a set of JAX-RS API resource classes, ensuring a consistent Swagger engine configuration with the Holon Platform property model support.

The `read(Set<Class<?>> classes)` method reads and generates a Swagger API definition model which includes the given API resource classes operations.

==== Swagger version 2 `ApiReader`

The link:{apidir}/com/holonplatform/jaxrs/swagger/v2/SwaggerV2.html[SwaggerV2^] entrypoint interface can be used to obtain an `ApiReader`, using a `SwaggerConfig` type configuration definition and providing a `io.swagger.models.Swagger` type API definition model.

Furthermore, the `SwaggerV2` interface provides a set of convenience methods to serialize the Swagger model using *JSON* (through the `asJson(...)` methods) or *YAML* (through the `asYaml(...)` methods).

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=apireaderv2,indent=0]
----
<1> Obtain a `ApiReader` using the provided configuration
<2> Generate the Swagger API model from given API resource classes
<3> Serialize the API model using JSON
<4> Serialize the API model using YAML

==== Swagger/OpenAPI version 3 `ApiReader`

The link:{apidir}/com/holonplatform/jaxrs/swagger/v3/SwaggerV3.html[SwaggerV3^] entrypoint interface can be used to obtain an `ApiReader`, using a `OpenAPIConfiguration` type configuration definition and providing a `io.swagger.v3.oas.models.OpenAPI` type API definition model.

Furthermore, the `SwaggerV3` interface provides a set of convenience methods to serialize the Swagger/OpenAPI model using *JSON* (through the `asJson(...)` methods) or *YAML* (through the `asYaml(...)` methods).

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=apireaderv3,indent=0]
----
<1> Obtain a `ApiReader` using the provided configuration
<2> Generate the OpenAPI model from given API resource classes
<3> Serialize the API model using JSON
<4> Serialize the API model using YAML

[[SwaggerSpringBoot]]
=== Spring Boot integration

The `holon-jaxrs-swagger` provides Spring Boot auto-configuration classes to automatically configure *Swagger API listing JAX-RS endpoints* in a Spring Boot application.

The Swagger auto-configuration is triggered when either a `ResourceConfig` type _Jersey_ configuration bean or a `ResteasyConfig` type _Resteasy_ configuration bean is available in Spring context.

==== Swagger API documentation endpoints configuration using properties

The Swagger auto-configuration relies on the `holon.swagger.*` configuration properties listed in the link:{apidir}/com/holonplatform/jaxrs/swagger/spring/SwaggerConfigurationProperties.html[SwaggerConfigurationProperties^] class to configure the Swagger API endpoints.

TIP: Just like any other Spring Boot configuration property, the `holon.swagger.*` properties can be specified in your inside your `application.properties` / `application.yml` file or as command line switches.

At least the `holon.swagger.resource-package` property, which specifies the Java _package_ name to scan to detect the JAX-RS API endpoints, must be setted to auto-configure a Swagger API listing endpoint. See <<SwaggerConfigurationProperties>> for a list of all available configuration properties.

By default, the `/api-docs` default path is used to expose the API listing endpoint, but can be changed using the `holon.swagger.path` property.

The API listing endpoint supports the `type` query parameter name to obtain the Swagger API definitions either in *JSON*, using the `json` parameter value (the default format), or in *YAML*, using the `yaml` parameter value.

For example, for a configuration like the following:

.application.yml
[source, yaml]
----
holon:
  swagger:
    version: "v1"
    title: "Test Swagger API"
    resource-package: "my.api.endpoints"
    path: "docs"
    pretty-print: true
----

The `my.api.endpoints` package is scanned to detect JAX-RS API resources and the API listing endpoint will be available at the `http(s):host/docs` URL.

===== Configure multiple API listing endpoints

Multiple API listing endpoints configuration is supported using the `holon.swagger.api-groups` configuration property, which accept a list of API _groups_, each bound to a specific API _package_ to scan and which can be independently configured using the <<SwaggerConfigurationProperties>>.

For each API group, an API listing endpoint will be available at the base API listing path (`/api-docs` by default, or the one configured with the `holon.swagger.path` property at the root level) followed by the `group-id` property name. For example: `http(s):host/api-docs/one`.

If a `group-id` is not specified, the `default` group id will be used and the API listing endpoint will be available at the base API listing path.

For example, for a configuration like the following:

.application.yml
[source, yaml]
----
holon:
  swagger:
    version: "v1"
    title: "Test Swagger API"
    
    api-groups:
      - group-id: "one" 
        resource-package: "my.api.endpoints.one"
        description: "The API group 1"
        path: docs/one
      - group-id: "two"
        resource-package: "my.api.endpoints.two"
        description: "The API group 2"
        path: docs/two
----

Two API groups are defined:

* The group 1, bound to the `my.api.endpoints.one` package and for which the API listing endpoint will be available at the `http(s):host/docs/one` URL.
* The group 2, bound to the `my.api.endpoints.two` package and for which the API listing endpoint will be available at the `http(s):host/docs/two` URL.

[[SwaggerConfigurationProperties]]
==== Swagger configuration properties

.Common configuration properties
|===
|Name |Meaning

|_holon.swagger._ *enabled*
|Whether the Swagger API listing endpoints auto-configuration is enabled. Default is `true`.

|_holon.swagger._ *resourcePackage*
|The package name to scan to detect API endpoints

|_holon.swagger._ *path*
|API listing endpoint path. When at group level, is appended to the base API listing path.

|_holon.swagger._ *schemes*
|API supported protocol schemes list (`http`, `https`)

|_holon.swagger._ *title*
|API title

|_holon.swagger._ *version*
|API version

|_holon.swagger._ *description*
|API description

|_holon.swagger._ *termsOfServiceUrl*
|Terms of Service URL

|_holon.swagger._ *contact*
|Contact information

|_holon.swagger._ *license*
|License information

|_holon.swagger._ *licenseUrl*
|License URL

|_holon.swagger._ *host*
|API host name

|_holon.swagger._ *pretty-print*
|Whether to _pretty_ format API listing output (`true` or `false`)

|_holon.swagger._ *api-groups*
|Optional API groups. Each group can be configured using the properties listed below.
|===

.API group configuration properties
|===
|Name |Meaning

|_holon.swagger.api-groups._ *group-id*
|API group id, also used as API listing endpoint sub-path is group `path` is not specified

|_holon.swagger.api-groups._ *resourcePackage*
|The package name to scan to detect API group endpoints

|_holon.swagger.api-groups._ *path*
|API group listing endpoint path

|_holon.swagger.api-groups._ *schemes*
|API group supported protocol schemes list (`http`, `https`)

|_holon.swagger.api-groups._ *title*
|API group title

|_holon.swagger.api-groups._ *version*
|API group version

|_holon.swagger.api-groups._ *description*
|API group description

|_holon.swagger.api-groups._ *termsOfServiceUrl*
|Terms of Service URL

|_holon.swagger.api-groups._ *contact*
|Contact information

|_holon.swagger.api-groups._ *license*
|License information

|_holon.swagger.api-groups._ *licenseUrl*
|License URL
|===

[[SwaggerAPIEndpointAutoConfiguration]]
==== Swagger API documentation endpoints auto-configuration

If the `holon.swagger.resourcePackage` configuration property is not provided and no API groups are defined using the `holon.swagger.apiGroups.*` configuration properties, the Holon Swagger integration module will try to auto-configure the Swagger API listing endpoints, relying on the Swagger `@Api` annotation.

IMPORTANT: Any JAX-RS `@Path` resource declared as a Spring bean which is annotated with the Swagger `@Api` annotation will be auto-detected and used to obtain the package name to use as Swagger API listing endpoint source.

The default `/api-docs` path is used as the Swagger API listing mapping.

To configure the API listing path and the API information properties, the link:{apidir}/com/holonplatform/jaxrs/swagger/annotations/ApiDefinition.html[ApiDefinition^] annotation can be used. The `@ApiDefinition` annotation can be used at package level (annotating a standard `package-info.java` class) or at resource class level.

The `@ApiDefinition` allows to setup the Swagger API documentation general informations, providing attributes to set the same information which can be configured using the <<SwaggerConfigurationProperties>> property set.

For example, given the following endpoint class:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=swagger1,indent=0]
----
<1> Standard Swagger `@Api` annotation to scan and include the endopoint class in the API documentation
<2> The API documentation _title_ is defined using the `@ApiDefinition` annotation
<3> Declare the endpoint as a Spring bean
<3> Standard Swagger annotations for the API documentation generation.

A Swagger API listing endpoint will be automatic configured and mapped to the default JAX-RS path: `/api-docs`.

To provide a different API listing endpoint mapping path, the `@ApiDefinition` annotation `value` can be used:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=swagger2,indent=0]
----
<1> Map the Swagger API listing endpoint to the `/docs` path

===== Multiple JAX-RS endpoint resources auto-configuration

When more than one JAX-RS endpoint is auto-configured for Swagger API documentation, you must pay attention to the declared Swagger API listing endpoint **paths** declared using the `@ApiDefinition` annotation.

All the JAX-RS endpoint classes bound to the same Swagger API documentation **path** will be merged into a **single Swagger API documentation configuration**. The API documentation configuration properties, if any, will be obtained form the available `@ApiDefinition` annotations which refer to the same path.

WARNING: When the `@ApiDefinition` annotations attributes declared for the same path are not consistent, a configuration exception will be thrown at application startup. For example, if two JAX-RS endpoint classes are annotated with `@ApiDefinition(value="/docs", title = "Title1")` and `@ApiDefinition(value="/docs", title = "Title2")` a configuration exception will be thrown, since a unique API title for the path `/docs` cannot be determined.

For example, given the following JAX-RS endpoints:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExampleSwagger.java[tag=swagger3,indent=0]
----
<1> Set the API listing path to `/docs1` and the API title to `Title 1`
<2> Set the API listing path to `/docs1`
<3> Set the API listing path to `/docs2` and the API title to `Title 2`

Two Swagger API listing endpoints will be auto-configured:

* One mapped to the `/docs1` path, which will provide the documentation for both `ExampleEndpoint3a` and `ExampleEndpoint3b` operations. The configured API title will be `Title 1`.

* Another mapped to the `/docs2` path, which will only provide the documentation for the `ExampleEndpoint3c` operations. The configured API title will be `Title 2`.

[[V2andV3]]
=== Enabling Swagger V2 and V3 API endpoints simultaneously

TBD
