= Holon Platform JAX-RS Module - Reference manual
:description: Holon platform JAX-RS module reference documentation. \
It concerns the platform JAX-RS and REST services support, including authentication and authorization, JWT support, Jersey and Resteasy integration, Swagger OpenAPI support, Spring framework integration and Spring Boot auto-configuration.
:revnumber: {project-version}
:apidir: ../api/holon-jax-rs
:coreapidir: ../api/holon-core
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 3

Copyright © 2016-2018

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

The Holon Platform *JAX-RS* module provides support, components and configuration helpers concerning the link:https://github.com/jax-rs/spec/blob/master/spec.pdf[JAX-RS^] - _Java API for RESTful Web Services_.

The module provides *JAX-RS* implementations and integrations for platform foundation components and structures, such as the link:holon-core.html#RestClient[RestClient] API, server-side authentication and authorization using a link:holon-core.html#Realm[Realm] and a complete link:http://swagger.io[Swagger^] _OpenAPI_ support for data containers such as link:holon-core.html#PropertyBox[PropertyBox].

Regarding the *JSON* data-interchange format, this module uses the link:holon-json.html[Holon JSON module] to make available the Holon platform JSON extensions and configuration facilities for JAX-RS endpoints and clients, allowing to seamlessy use link:https://github.com/FasterXML/jackson[Jackson^] or link:https://github.com/google/gson[Gson^] as JSON providers and provide support for _temporal_ types (including the `java.time.*` API) and the `PropertyBox` type out-of-the-box. 

Furthermore, the module makes available a set of *auto-configuration* features, both for the JAX-RS ecosystem and for the link:https://spring.io[Spring^] and link:https://projects.spring.io/spring-boot[Spring Boot^] world.

A complete support for the most used JAX-RS implementations (link:https://github.com/jersey[Jersey^] and  link:http://resteasy.jboss.org[Resteasy^]) is provided, including Resteasy auto-configuration classes for Spring Boot integration.

== Obtaining the artifacts

The Holon Platform uses https://maven.apache.org[Maven^] for projects build and configuration. All the platform artifacts are published in the *Maven Central Repository*, so there is no need to explicitly declare additional repositories in your project `pom` file.

At the top of each _section_ of this documentation you will find the Maven _coordinates_ (group id, artifact id and version) to obtain the artifact(s) as a dependency for your project.

A *BOM (Bill Of Materials)* `pom` is provided to import the available dependencies for a specific version in your projects. The Maven coordinates for the core BOM are the following:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-bom</artifactId>
<version>{revnumber}</version>
----

The BOM can be imported in a Maven project in the following way:

[source, xml, subs="verbatim,quotes,attributes+"]
----
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.holon-platform.jaxrs</groupId>
			<artifactId>holon-jaxrs-bom</artifactId>
			<version>{revnumber}</version>
			*<type>pom</type>*
			*<scope>import</scope>*
		</dependency>
	</dependencies>
</dependencyManagement>
----

=== Using the Platform BOM

The Holon Platform provides an *overall Maven BOM (Bill of Materials)* to easily obtain all the available platform artifacts.

See link:index.html#obtain-the-platform-artifacts[Obtain the platform artifacts] for details.

[[WhatsNew51x]]
== What's new in version 5.1.x

* Improved support for the `java.time.*` Date and Time API data types when a `PropertyBox` type is serialized and deserialize as *JSON* in JAX-RS endpoints. See <<JSONMediaTypePropertyBox>>.

* The new `JaxrsAuthenticationInspector` API is available in JAX-RS endpoints to inspect current `Authentication` and perform authorization controls using a JAX-RS `SecurityContext`. See <<JaxrsAuthenticationInspector>>.

* Improved *Spring Boot* auto-configuration support for _Jersey_ and _Resteasy_ JAX-RS implementations. See <<JaxrsSpringBoot>>.

* Improved link:https://swagger.io[Swagger^] integration and auto-configuration, using Spring Boot application properties for easier configuration. See <<SwaggerSpringBoot,Swagger Spring Boot integration>>.

[[JaxrsPropertyBox]]
== `PropertyBox` serialization and deserialization support

The link:holon-core.html#PropertyBox[PropertyBox] type serialization and deserialization support for JAX-RS compliant servers and clients is available using the following _media types_:

* `application/json` - see <<JSONMediaTypePropertyBox>>
* `application/x-www-form-urlencoded` - see <<FormMediaTypePropertyBox>>

[[JSONMediaTypePropertyBox]]
=== JSON media type

The *JSON* serialization and deserialization support for the `PropertyBox` type is provided by the link:holon-json[Holon Platform JSON module]. Both https://github.com/FasterXML/jackson[Jackson^] and link:https://github.com/google/gson[Gson^] JSON providers are supported.

To learn about `PropertyBox` type mapping strategies and configuration options see the link:holon-json#PropertyBox[PropertyBox] section of the Holon Platform JSON module documentation.

To enable the `PropertyBox` type support for JSON media type, just ensure that a suitable artifact is present in classpath:

* `holon-jackson-jaxrs` to use the *Jackson* library. See link:holon-json#JacksonJAXRS[Jackson JAX-RS integration] for details.
* `holon-gson-jaxrs` to use the *Gson* library. See link:holon-json#GsonJAXRS[Gson JAX-RS integration] for details.

The auto-configuration facilities provided by this two artifacts allow to automatically register and setup all the required JAX-RS features, both for link:https://github.com/jersey[Jersey^] and for link:http://resteasy.jboss.org[Resteasy^] JAX-RS implementations.

With the `PropertyBox` _JSON_ support enabled, you can write JAX-RS endpoints like this:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExamplePropertyBox.java[tag=json,indent=0]
----
<1> A `GET` endpoint method which returns a JSON-encoded `PropertyBox` instance
<2> A `GET` endpoint method which returns a JSON-encoded `PropertyBox` instances `List`
<3> A `PUT` endpoint method which accepts a JSON-encoded `PropertyBox` as body parameter. The `@PropertySetRef` annotation is used to specify the `PropertySet` to be used to decode the `PropertyBox` from JSON

[[FormMediaTypePropertyBox]]
=== Form/URLencoded media type

The `application/x-www-form-urlencoded` media type for `PropertyBox` serialization and deserialization is supported by default and auto-configured for _Jersey_ and _Resteasy_ when the `holon-jaxrs-commons` artifact is present in classpath.

You can explicitly configure the `application/x-www-form-urlencoded` media type support in a JAX-RS server or client registering the link:{apidir}/com/holonplatform/jaxrs/media/FormDataPropertyBoxFeature.html[FormDataPropertyBoxFeature^].

CAUTION: Only *simple data types* (Strings, Numbers, Booleans, Enums and Dates) are supported for `PropertyBox` serialization and deserialization using the `application/x-www-form-urlencoded` media type, so you cannot use complex property values (such as Java beans) as `PropertyBox` property values. The *JSON* media type is strongly recommended as `PropertyBox` data interchange format in a JAX-RS environment.

With the _form/urlencoded_ `PropertyBox` type support enabled, you can write JAX-RS endpoints like this:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExamplePropertyBox.java[tag=form,indent=0]
----
<1> A `POST` endpoint method which accepts a JSON-encoded `PropertyBox` as body parameter. The `@PropertySetRef` annotation is used to specify the `PropertySet` to be used to decode the `PropertyBox` from `application/x-www-form-urlencoded` data

// Inclusions

include::_client.adoc[]

include::_server.adoc[]

include::_spring.adoc[]

include::_swagger.adoc[]

== Loggers

By default, the Holon platform uses the https://www.slf4j.org[SLF4J^] API for logging. The use of SLF4J is optional: it is enabled when the presence of SLF4J is detected in the classpath. Otherwise, logging will fall back to JUL (`java.util.logging`).

The logger names for the *JAX-RS* module are:

* `com.holonplatform.jaxrs` base JAX-RS module logger
* `com.holonplatform.jaxrs.swagger` for the _Swagger_ integration classes

== System requirements

=== Java

The Holon Platform JSON module requires https://www.java.com[Java] *8* or higher.

The _JAX-RS_ specification version *2.0 or above* is required.

This module is tested against link:https://github.com/jersey[Jersey^] version *2.x* and link:http://resteasy.jboss.org[Resteasy^] version *3.x*.
