= Holon JAX-RS integration
:revnumber: {project-version}
:apidir: ../api/holon-jax-rs
:coreapidir: ../api/holon-core
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 3

Copyright © 2016-2017

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

The Holon Platform *JAX-RS* module provides support, components and configuration helpers concerning the link:https://github.com/jax-rs/spec/blob/master/spec.pdf[JAX-RS^] - _Java API for RESTful Web Service_ standard.

The module provides *JAX-RS* implementations and integrations for platform foundation components and structures, such as the link:holon-core.html#RestClient[RestClient] API, server-side authentication and authorization using a link:holon-core.html#Realm[Realm] and a complete link:http://swagger.io[Swagger^] _OpenAPI_ support for data containers such as link:holon-core.html#PropertyBox[PropertyBox].

Furthermore, the module makes available a set of *auto-configuration* features, both for the _JAX-RS_ ecosystem and for the *Spring* and *Spring Boot* world.

== Obtaining the artifacts

The Holon Platform uses https://maven.apache.org[Maven^] for projects build and configuration. All the platform artifacts are published in the *Maven Central Repository*, so there is no need to explicitly declare additional repositories in your project `pom` file.

At the top of each _section_ of this documentation you will find the Maven _coordinates_ (group id, artifact id and version) to obtain the artifact(s) as a dependency for your project.

A *BOM (Bill Of Materials)* `pom` is provided to import the available dependencies for a specific version in your projects. The Maven coordinates for the core BOM are the following:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.jaxrs</groupId>
<artifactId>holon-jaxrs-bom</artifactId>
<version>{revnumber}</version>
----

The BOM can be imported in a Maven project in the following way:

[source, xml, subs="verbatim,quotes,attributes+"]
----
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.holon-platform.jaxrs</groupId>
			<artifactId>holon-jaxrs-bom</artifactId>
			<version>{revnumber}</version>
			*<type>pom</type>*
			*<scope>import</scope>*
		</dependency>
	</dependencies>
</dependencyManagement>
----

=== Using the Platform BOM

The Holon Platform provides an *overall Maven BOM (Bill of Materials)* to easily obtain all the available platform artifacts.

See link:index.html#obtain-the-platform-artifacts[Obtain the platform artifacts] for details.

== `PropertyBox` serialization and deserialization support

The link:holon-core.html#PropertyBox[PropertyBox] data container serialization and deserialization support for JAX-RS compliant servers and clients is available using the following _media types_:

* `application/json` - see <<JSONMediaTypePropertyBox>>
* `application/x-www-form-urlencoded` - see <<FormMediaTypePropertyBox>>

[[JSONMediaTypePropertyBox]]
=== JSON media type

The *JSON* serialization and deserialization support for `PropertyBox` is provided by the link:holon-json[Holon Platform JSON module]. Both link:http://wiki.fasterxml.com/JacksonHome[Jackson] and link:https://github.com/google/gson[Gson] JSON processors are supported.

Just ensure the suitable artifact is present in classpath to auto-configure the required _providers_ and _context resolvers_ for a JAX-RS server and/or client to enable *JSON* serialization and deserialization support for `PropertyBox`:

* `com.holon-platform.json` / `holon-jackson-jaxrs` for JSON support using *Jackson*
* `com.holon-platform.json` / `holon-gson-jaxrs` for JSON support using *Gson*

See the link:holon-json[Holon Platform JSON module documentation] for details and configuration options.

With the `PropertyBox` _JSON_ support enabled, you can write JAX-RS endpoints like this:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExamplePropertyBox.java[tag=json,indent=0]
----
<1> A `GET` endpoint method which returns a JSON-encoded `PropertyBox` instance
<2> A `GET` endpoint method which returns a JSON-encoded `PropertyBox` instances `List`
<3> A `PUT` endpoint method which accepts a JSON-encoded `PropertyBox` as body parameter. The `@PropertySetRef` annotation is used to specify the `PropertySet` to be used to decode the `PropertyBox` from JSON

[[FormMediaTypePropertyBox]]
=== Form/URLencoded media type

The `application/x-www-form-urlencoded` media type for `PropertyBox` serialization and deserialization is supported by default and auto-configured when one of the artifacts of the *JAX-RS* is present in classpath.

You can explicitly configure the `application/x-www-form-urlencoded` media type support in a JAX-RS server or client registering the link:{apidir}/com/holonplatform/jaxrs/media/FormDataPropertyBoxFeature.html[FormDataPropertyBoxFeature^].

CAUTION: Only *simple data types* (Strings, Numbers, Booleans, Enums and Dates) are supported for `PropertyBox` serialization and deserialization using the `application/x-www-form-urlencoded` media type, so you cannot use complex property values (such as JavaBeans) as `PropertyBox` property values. The *JSON* media type is strongly recommended as `PropertyBox` data interchange format in a JAX-RS environment.

With the `PropertyBox` for the _form/urlencoded_ format support enabled, you can write JAX-RS endpoints like this:

[source, java]
----
include::{examplesdir}/com/holonplatform/jaxrs/examples/ExamplePropertyBox.java[tag=form,indent=0]
----
<1> A `POST` endpoint method which accepts a JSON-encoded `PropertyBox` as body parameter. The `@PropertySetRef` annotation is used to specify the `PropertySet` to be used to decode the `PropertyBox` from `application/x-www-form-urlencoded` data

// Inclusions

include::_client.adoc[]

include::_server.adoc[]

include::_swagger.adoc[]

include::_spring.adoc[]

== Loggers

By default, the Holon platform uses the https://www.slf4j.org[SLF4J^] API for logging. The use of SLF4J is optional: it is enabled when the presence of SLF4J is detected in the classpath. Otherwise, logging will fall back to JUL (`java.util.logging`).

The logger names for the *JAX-RS* module are:

* `com.holonplatform.jaxrs` base JAX-RS module logger
* `com.holonplatform.jaxrs.swagger` for the _Swagger_ integration classes

== System requirements

=== Java

The Holon Platform JSON module requires https://www.java.com[Java] *8* or higher.

The _JAX-RS_ specification version *2.0 or above* is required.

This module is tested against link:https://github.com/jersey[Jersey^] version *2.x* and link:http://resteasy.jboss.org[Resteasy^] version *3.x*.
